apiVersion: spinnaker.io/v1alpha2
kind: SpinnakerAccount
metadata:
  name: spinnaker-default
spec:
  type: Kubernetes
  enabled: true
  permissions: {} # List of permissions - see below
  settings: {} # Settings see below
  kubernetes:
    kubeconfigSecret:
      name: spin-secrets
      key: kubeconfig